version: "3.8"

services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CONTENT_SERVER_URL=http://localhost:3001
      - NEXT_PUBLIC_IMAGE_ANALYSIS_URL=http://localhost:3003
    depends_on:
      - content-server
      - image-analysis
    networks:
      - vaultcast-network
    restart: unless-stopped

  content-server:
    build:
      context: ./content-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEXT_APP_URL=http://website:3000
    volumes:
      - ./content-server/media:/app/media
    networks:
      - vaultcast-network
    restart: unless-stopped

  image-analysis:
    build:
      context: ./image-analysis
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_VISION_API_KEY=${GOOGLE_VISION_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - ALLOWED_ORIGINS=http://localhost:3000,http://website:3000
      - ENABLE_TENSORFLOW_MODELS=true
    volumes:
      - image-analysis-uploads:/app/uploads
      - image-analysis-models:/app/models
    networks:
      - vaultcast-network
    restart: unless-stopped

volumes:
  image-analysis-uploads:
  image-analysis-models:

networks:
  vaultcast-network:
    driver: bridge
