apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultcast-config
  namespace: vaultcast
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_CONTENT_SERVER_URL: "http://content-server-service:3001"
  NEXT_PUBLIC_IMAGE_ANALYSIS_URL: "http://image-analysis-service:3003"
  NEXT_APP_URL: "http://website-service:3000"
  ALLOWED_ORIGINS: "http://localhost:3000,http://website-service:3000"
  ENABLE_TENSORFLOW_MODELS: "true"
  PORT_WEBSITE: "3000"
  PORT_CONTENT_SERVER: "3001"
  PORT_IMAGE_ANALYSIS: "3003"
