apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-server
  namespace: vaultcast
  labels:
    app: content-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-server
  template:
    metadata:
      labels:
        app: content-server
    spec:
      containers:
        - name: content-server
          image: vaultcast-content-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: media-volume
              mountPath: /app/uploads
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: content-server-media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: content-server-service
  namespace: vaultcast
spec:
  selector:
    app: content-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: NodePort
