apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: vaultcast
  labels:
    app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: vaultcast-website:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: CONTENT_SERVER_URL
              value: "http://content-server-service:3001"
            - name: IMAGE_ANALYSIS_URL
              value: "http://image-analysis-service:3003"
            - name: NEXT_PUBLIC_CONTENT_SERVER_URL
              value: "http://content-server-service:3001"
            - name: NEXT_PUBLIC_FILES_URL
              value: "http://content-server-service:3001"
            - name: NEXT_PUBLIC_BASE_URL
              value: "http://website-service:3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: vaultcast
spec:
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
